// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Apps: typeof import('./src/components/Apps.vue')['default']
    BarChart: typeof import('./src/components/BarChart.vue')['default']
    BreakdownMessage: typeof import('./src/components/BreakdownMessage.vue')['default']
    BreakdownRequest: typeof import('./src/components/BreakdownRequest.vue')['default']
    DeleteTodo: typeof import('./src/components/DeleteTodo.vue')['default']
    DownloadLinks: typeof import('./src/components/DownloadLinks.vue')['default']
    Encryption: typeof import('./src/components/Encryption.vue')['default']
    FrogsMessage: typeof import('./src/components/FrogsMessage.vue')['default']
    HeroProfile: typeof import('./src/components/HeroProfile.vue')['default']
    IndexCircle: typeof import('./src/components/IndexCircle.vue')['default']
    Loader: typeof import('./src/components/Loader.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    OrangeBubble: typeof import('./src/components/TodoCard/OrangeBubble.vue')['default']
    Progress: typeof import('./src/components/Progress.vue')['default']
    QRCode: typeof import('./src/components/QRCode.vue')['default']
    Reviews: typeof import('./src/components/Reviews.vue')['default']
    Rules: typeof import('./src/components/Rules.vue')['default']
    Snackbar: typeof import('./src/components/Snackbar.vue')['default']
    Support: typeof import('./src/components/Support.vue')['default']
    TodoCard: typeof import('./src/components/TodoCard/TodoCard.vue')['default']
    TodoCardActions: typeof import('./src/components/TodoCard/TodoCardActions.vue')['default']
    TodoCardModifiers: typeof import('./src/components/TodoCard/TodoCardModifiers.vue')['default']
    TodoForm: typeof import('./src/components/TodoForm/TodoForm.vue')['default']
    TodoText: typeof import('./src/components/TodoCard/TodoText.vue')['default']
    'VertiсalProgressBar': typeof import('./src/components/VertiсalProgressBar.vue')['default']
  }
}

export { }
